baseurl = "https://roverserver.eu.org"
DefaultContentLanguage = "de"
title = "Der Roverserver"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Lust andere Rover (und sich der Stufe verbunden fühlende Menschen) kennenzulernen?"
  mainSections = ["post","posts"]
  logo = "/img/logo.png" # Expecting square dimensions
  favicon = "/favicon/favicon.svg"
  dateFormat = "2.1.2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = true
  selfHosted = true

[Params.footer]
  text = "[Impressum und Datenschutz](/impressum)"

#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
#   name = "Some Person"
#   website = "yourwebsite.com"
  email = "team@discord.rover.de"
#   facebook = "username"
  github = "roverserver"
#   gitlab = "username"
#   bitbucket = "username"
#   twitter = "username"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"
#   500px = "username"
#   codepen = "username"
#   mastodon = "url"
#   kaggle = "username"
#   weibo = "username"utton
#   slack = "username"
  discord = "RANtB5d4us"
#   strava = "userid"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = ':slug'


# [[menu.main]]
#     name = "Tags"
#     url = "tags"
#     weight = 5
